name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sqlite3
      - name: Initialise database
        run: php scripts/init-db.php
      - name: PHP lint
        run: |
          php -l common.php
          php -l api.php
          php -l index.php
          php -l print.php
